language: java
jdk: openjdk8

script:
  - ./mvnw clean package

deploy:
  provider: script
  script: ./mvnw deploy -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_TOKEN
  on:
    branch: master
