services:
  - docker

jobs:
  include:
    - stage: build
      language: java
      cache:
        directories:
          - $HOME/.m2
      script:
        - ./mvnw clean package
        - docker images
    - stage: deploy
      branches:
        only:
          - master
      language: python
      python: "3.8"
      install:
        - pip install pipenv
        - pipenv install
      script:
        - docker images
        - python deploy/deploy.py