language: java
jdk: openjdk8

services:
  - docker

cache:
  - $MAVEN_HOME/.m2/repositories

script:
  - ./mvnw clean package

deploy:
  provider: script
  script: bash ./docker-deploy.sh
  on:
    branch: master
