language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

services:
  - docker

jobs:
  include:
    - stage: dev
      script:
        - ./mvnw clean verify -Pdev -Drevision=
      branches:
        except:
          - master
    - stage: prod
      before_script:
        - bash scripts/docker-version-validation.sh
      script:
        - ./mvnw clean deploy -Pprod -Drevision=
      branches:
        only:
          - master