services:
  - docker

jobs:
  include:
    - stage: build
      language: java
      cache:
        directories:
        - $MAVEN_HOME/.m2/repositories
      script:
        - ./mvnw clean package
    - stage: deploy
      branches:
        only:
          - master
      language: python
      python: "3.8"
      install:
        - pip install pipenv
        - pipenv install
      script:
        - python deploy.py